/*
  Adds business fields required by the fleet Tyre Master screen
  to the existing TIRE_MASTER table.
*/

IF COL_LENGTH('dbo.TIRE_MASTER', 'KM_RUN') IS NULL
BEGIN
    ALTER TABLE [dbo].[TIRE_MASTER]
    ADD [KM_RUN] NUMERIC(18, 2) NULL;
END;

IF COL_LENGTH('dbo.TIRE_MASTER', 'WARRANTY_YEARS') IS NULL
BEGIN
    ALTER TABLE [dbo].[TIRE_MASTER]
    ADD [WARRANTY_YEARS] INT NULL;
END;

IF COL_LENGTH('dbo.TIRE_MASTER', 'WARRANTY_KM') IS NULL
BEGIN
    ALTER TABLE [dbo].[TIRE_MASTER]
    ADD [WARRANTY_KM] NUMERIC(18, 2) NULL;
END;

IF COL_LENGTH('dbo.TIRE_MASTER', 'PURCHASE_WITH_TAX') IS NULL
BEGIN
    ALTER TABLE [dbo].[TIRE_MASTER]
    ADD [PURCHASE_WITH_TAX] NUMERIC(18, 2) NULL;
END;

IF COL_LENGTH('dbo.TIRE_MASTER', 'PURCHASE_WITHOUT_TAX') IS NULL
BEGIN
    ALTER TABLE [dbo].[TIRE_MASTER]
    ADD [PURCHASE_WITHOUT_TAX] NUMERIC(18, 2) NULL;
END;
