-- Migrate document columns to VARBINARY(MAX) to store files directly in the database

-- Step 1: Nullify existing string paths (since they are no longer usable and just point to a dead folder)
UPDATE FLEET_EQUIPMENT_MASTER SET IMAGE = NULL, FITNESS_DOC = NULL, RC_DOC = NULL, INSURANCE_DOC = NULL, PERMIT_A = NULL, PERMIT_B = NULL;

-- Step 2: Drop the old VARCHAR columns and Add them back as VARBINARY(MAX)
ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN IMAGE;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD IMAGE VARBINARY(MAX);

ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN FITNESS_DOC;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD FITNESS_DOC VARBINARY(MAX);

ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN RC_DOC;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD RC_DOC VARBINARY(MAX);

ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN INSURANCE_DOC;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD INSURANCE_DOC VARBINARY(MAX);

ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN PERMIT_A;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD PERMIT_A VARBINARY(MAX);

ALTER TABLE FLEET_EQUIPMENT_MASTER DROP COLUMN PERMIT_B;
ALTER TABLE FLEET_EQUIPMENT_MASTER ADD PERMIT_B VARBINARY(MAX);

PRINT 'Columns successfully converted to VARBINARY(MAX)';
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FLEET_EQUIPMENT_MASTER'
  AND COLUMN_NAME IN ('IMAGE','FITNESS_DOC','RC_DOC','INSURANCE_DOC','PERMIT_A','PERMIT_B');
