-- 1. Vehicle Master (Both Fleet and Legacy tables, just to be safe)
IF COL_LENGTH('dbo.FLEET_EQUIPMENT_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.FLEET_EQUIPMENT_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

IF COL_LENGTH('dbo.VEHICLE_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.VEHICLE_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 2. Driver Master
IF COL_LENGTH('dbo.DRIVER_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.DRIVER_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 3. Tyre Master
IF COL_LENGTH('dbo.TIRE_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.TIRE_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 4. Tyre Position Master
IF COL_LENGTH('dbo.TIRE_POSITION_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.TIRE_POSITION_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 5. Bed Master
IF COL_LENGTH('dbo.BED_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.BED_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 6. Bed Attachment / Detach History
IF COL_LENGTH('dbo.BED_ATTACHMENT_HISTORY', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.BED_ATTACHMENT_HISTORY ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 7. Job Order
IF COL_LENGTH('dbo.JOB_ORDER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.JOB_ORDER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 8. Job Order Close
IF COL_LENGTH('dbo.JOB_ORDER_CLOSE', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.JOB_ORDER_CLOSE ADD TERMINAL_ID NUMERIC(18, 0) NULL;

-- 9. Vendor Master
IF COL_LENGTH('dbo.VENDOR_MASTER', 'TERMINAL_ID') IS NULL
    ALTER TABLE dbo.VENDOR_MASTER ADD TERMINAL_ID NUMERIC(18, 0) NULL;

PRINT 'Data Isolation / Terminal IDs added correctly.';
