-- Email configuration master (admin managed)

IF OBJECT_ID('dbo.EMAIL_CONFIG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EMAIL_CONFIG (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PROVIDER VARCHAR(50) NULL,
    SMTP_HOST VARCHAR(255) NULL,
    SMTP_PORT INT NULL,
    SMTP_SECURE BIT NOT NULL CONSTRAINT DF_EMAIL_CONFIG_SMTP_SECURE DEFAULT(0),
    SMTP_USER VARCHAR(255) NULL,
    SMTP_PASS_ENC VARBINARY(MAX) NULL,
    FROM_EMAIL VARCHAR(255) NULL,
    FROM_NAME VARCHAR(255) NULL,
    REPLY_TO VARCHAR(255) NULL,
    IS_ACTIVE BIT NOT NULL CONSTRAINT DF_EMAIL_CONFIG_IS_ACTIVE DEFAULT(1),
    CREATED_AT DATETIME NOT NULL CONSTRAINT DF_EMAIL_CONFIG_CREATED_AT DEFAULT(GETDATE()),
    UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_EMAIL_CONFIG_UPDATED_AT DEFAULT(GETDATE())
  );
END

-- Only one active config at a time
IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_EMAIL_CONFIG_SINGLE_ACTIVE'
    AND object_id = OBJECT_ID('dbo.EMAIL_CONFIG')
)
BEGIN
  CREATE UNIQUE INDEX UX_EMAIL_CONFIG_SINGLE_ACTIVE
  ON dbo.EMAIL_CONFIG (IS_ACTIVE)
  WHERE IS_ACTIVE = 1;
END

