
-- Migration to add TERMINAL_ID to key operational tables for Data Isolation
-- Created: 2026-04-17

-- 1. Transport Requests
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.transport_requests') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.transport_requests ADD TERMINAL_ID NUMERIC(18,0);
END

-- 2. Driver Master
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.DRIVER_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.DRIVER_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 3. Equipment Master (Vehicles)
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FLEET_EQUIPMENT_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.FLEET_EQUIPMENT_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 4. Tire Master
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.TIRE_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.TIRE_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 5. Bed Master
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BED_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.BED_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 6. Tire Attachment
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.TIRE_ATTACHMENT_HISTORY') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.TIRE_ATTACHMENT_HISTORY ADD TERMINAL_ID NUMERIC(18,0);
END

-- 7. Bed Attachment
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.BED_ATTACHMENT_HISTORY') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.BED_ATTACHMENT_HISTORY ADD TERMINAL_ID NUMERIC(18,0);
END

-- 8. Tire Position Master (if needed)
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.TIRE_POSITION_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.TIRE_POSITION_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 9. Job Orders
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.JOB_ORDER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.JOB_ORDER ADD TERMINAL_ID NUMERIC(18,0);
END

-- 10. ASN Master
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.ASN_MASTER') AND name = 'TERMINAL_ID')
BEGIN
    ALTER TABLE dbo.ASN_MASTER ADD TERMINAL_ID NUMERIC(18,0);
END
