-- Migration to add granular permissions to USER_PAGE_ACCESS_MAPPING
-- Created: 2026-04-17

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.USER_PAGE_ACCESS_MAPPING') AND name = 'CAN_VIEW')
BEGIN
    ALTER TABLE dbo.USER_PAGE_ACCESS_MAPPING ADD CAN_VIEW BIT DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.USER_PAGE_ACCESS_MAPPING') AND name = 'CAN_CREATE')
BEGIN
    ALTER TABLE dbo.USER_PAGE_ACCESS_MAPPING ADD CAN_CREATE BIT DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.USER_PAGE_ACCESS_MAPPING') AND name = 'CAN_EDIT')
BEGIN
    ALTER TABLE dbo.USER_PAGE_ACCESS_MAPPING ADD CAN_EDIT BIT DEFAULT 0;
END
GO

-- Update existing records to have View permission by default
UPDATE dbo.USER_PAGE_ACCESS_MAPPING 
SET CAN_VIEW = 1 
WHERE CAN_VIEW IS NULL OR CAN_VIEW = 0;
GO
